#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 10, 2019 05:36:00 PM IST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set desc "-family {DejaVu Sans} -size 0"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {DejaVu Sans Mono} -size 12"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 0"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Noto Sans CJK SC} -size 12 -weight bold -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font17
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1301x716+65+24
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#0d3f0e} -height 105 \
        -highlightcolor black -width 1275 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#54d854} \
        -font {-family {Noto Sans CJK SC} -size 23 -weight bold -slant italic} \
        -foreground {#000000} -highlightcolor black -text {Hi Admin!} 
    vTcl:DefineAlias "$site_3_0.lab44" "Label1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 300 -y 20 -width 676 -relwidth 0 -height 68 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background {#0d3f0e} -height 225 \
        -highlightcolor black -width 1275 
    vTcl:DefineAlias "$top.fra46" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#88d8a0} \
        -font {-family {Noto Sans CJK SC} -size 11 -weight bold -slant italic} \
        -foreground {#000000} -highlightcolor black \
        -text {Enter the video Path :} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label2" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex48 \
        -background white -font {-family {DejaVu Sans} -size 12} \
        -foreground black -height 52 -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 576 -wrap word 
    .top42.fra46.tex48 configure -font "-family {DejaVu Sans} -size 12"
    .top42.fra46.tex48 insert end text
    vTcl:DefineAlias "$site_3_0.tex48" "Text1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#36f44f} \
        -font {-family {Noto Sans CJK SC} -size 11 -weight bold -slant italic} \
        -foreground {#000000} -highlightcolor black -text Load 
    vTcl:DefineAlias "$site_3_0.but43" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but44 \
        -background {#36f44f} \
        -font {-family {Noto Sans CJK SC} -size 12 -weight bold -slant italic} \
        -foreground {#000000} -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_3_0.but44" "Button3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 300 -y 40 -width 206 -relwidth 0 -height 38 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex48 \
        -in $site_3_0 -x 300 -y 100 -width 576 -relwidth 0 -height 52 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but43 \
        -in $site_3_0 -x 950 -y 110 -width 89 -relwidth 0 -height 38 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but44 \
        -in $site_3_0 -x 1080 -y 110 -width 79 -relwidth 0 -height 38 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra49 \
        -borderwidth 2 -relief groove -background {#0d3f0e} -height 345 \
        -highlightcolor black -width 1275 
    vTcl:DefineAlias "$top.fra49" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra49
    button $site_3_0.but50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#8fd8a7} \
        -font {-family {Noto Sans CJK SC} -size 18 -weight bold -slant italic} \
        -foreground {#000000} -highlightcolor black \
        -text {Click here to add new resident} 
    vTcl:DefineAlias "$site_3_0.but50" "Button1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but50 \
        -in $site_3_0 -x 310 -y 150 -width 529 -relwidth 0 -height 68 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 10 -y 20 -width 1275 -relwidth 0 -height 105 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 10 -y 140 -width 1275 -relwidth 0 -height 225 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 10 -y 380 -width 1275 -relwidth 0 -height 345 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

