#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 10, 2019 05:35:58 PM IST  platform: Linux

import sys
from functools import partial
import knn_new_resident
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import knn_vdo_path_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    knn_vdo_path_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    knn_vdo_path_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1301x716+65+24")
        top.title("New Toplevel")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.008, rely=0.028, relheight=0.147, relwidth=0.98)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#0d3f0e")
        self.Frame1.configure(width=1275)

        self.Label1 = tk.Label(top)
        self.Label1= tk.Label(self.Frame1)
        self.Label1.place(relx=0.235, rely=0.19, height=68, width=676)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#54d854")
        self.Label1.configure(font="-family {Noto Sans CJK SC} -size 23 -weight bold -slant italic")
        self.Label1.configure(text='''Hi Admin!''')

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.008, rely=0.196, relheight=0.314, relwidth=0.98)

        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#0d3f0e")
        self.Frame2.configure(width=1275)

        self.Label1 = tk.Label(top)
        self.Label2 = tk.Label(self.Frame2)
        self.Label2.place(relx=0.235, rely=0.178, height=38, width=206)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="#88d8a0")
        self.Label2.configure(font="-family {Noto Sans CJK SC} -size 11 -weight bold -slant italic")
        self.Label2.configure(text='''Enter the video Path :''')

        self.Text1 = tk.Entry(top)
        self.Text1 = tk.Text(self.Frame2)
        self.Text1.place(relx=0.235, rely=0.444, relheight=0.231, relwidth=0.452)

        self.Text1.configure(background="white")
        self.Text1.configure(font="-family {DejaVu Sans} -size 12")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(width=576)
        self.Text1.configure(wrap="word")

        self.Button2 = tk.Button(top)
        self.Button2 = tk.Button(self.Frame2)
        self.Button2.place(relx=0.745, rely=0.489, height=38, width=89)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(background="#36f44f")
        self.Button2.configure(font="-family {Noto Sans CJK SC} -size 11 -weight bold -slant italic")
        self.Button2.configure(text='''Load''')
        self.Button2.configure(width=89)
        knn_vdo_path_handler = partial(knn_vdo_path_support.knn_vdo_path_handler, self, top)
        self.Button2.configure(command=knn_vdo_path_handler)

        self.Button3 = tk.Button(top)
        self.Button3 = tk.Button(self.Frame2)
        self.Button3.place(relx=0.847, rely=0.489, height=38, width=79)
        self.Button3.configure(background="#36f44f")
        self.Button3.configure(font="-family {Noto Sans CJK SC} -size 12 -weight bold -slant italic")
        self.Button3.configure(text='''Run''')
        self.Button3.configure(width=79)
        run = partial(knn_vdo_path_support.run, self, top)
        self.Button3.configure(command=run)

        self.Frame3 = tk.Frame(top)
        self.Frame3.place(relx=0.008, rely=0.531, relheight=0.482, relwidth=0.98)

        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#0d3f0e")
        self.Frame3.configure(width=1275)

        self.Button1 = tk.Button(top)
        self.Button1 = tk.Button(self.Frame3)
        self.Button1.place(relx=0.243, rely=0.435, height=68, width=529)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(background="#8fd8a7")
        self.Button1.configure(font="-family {Noto Sans CJK SC} -size 18 -weight bold -slant italic")
        self.Button1.configure(command = knn_new_resident.vp_start_gui,text='''Click here to add new resident''')
	

if __name__ == '__main__':
    vp_start_gui()





