#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 10, 2019 03:02:19 PM IST  platform: Linux

import sys
import MySQLdb

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import knn_new_resident_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    knn_new_resident_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    knn_new_resident_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def do(self):
        plt_no = self.Text3.get('1.0','end-1c')
        flat_no = self.Text2.get('1.0', 'end-1c')
        owner = self.Text1.get('1.0','end-1c')
        sql = "insert into resiInfo (plt_no,owner,flat_no) values ('"+ plt_no + "','" + owner + "','" + flat_no + "')"
        dbc = MySQLdb.connect("localhost", "root", "Sneha@1998", "plate")
        cursor = dbc.cursor()
        cursor.execute(sql)
        dbc.commit()
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1301x744+65+24")
        top.title("New Toplevel")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.008, rely=0.013, relheight=0.974, relwidth=0.98)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#22542d")
        self.Frame1.configure(width=1275)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.259, rely=0.055, height=58, width=516)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#82d890")
        self.Label1.configure(font="-family {Noto Sans CJK SC} -size 23 -weight bold -slant italic")
        self.Label1.configure(text='''New Resident Form''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.047, rely=0.234, height=28, width=106)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="#82d88a")
        self.Label2.configure(font="-family {Noto Sans CJK SC} -size 11 -weight bold -slant italic")
        self.Label2.configure(text='''Name''')

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.047, rely=0.29, relheight=0.044, relwidth=0.279)
        self.Text1.configure(background="white")
        self.Text1.configure(font="-family {DejaVu Sans} -size 12")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(width=356)
        self.Text1.configure(wrap="word")

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.047, rely=0.386, height=28, width=106)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(background="#82d88a")
        self.Label3.configure(font="-family {Noto Sans CJK SC} -size 11 -weight bold -slant italic")
        self.Label3.configure(text='''Flat_no.''')

        self.Text2 = tk.Text(self.Frame1)
        self.Text2.place(relx=0.047, rely=0.441, relheight=0.044, relwidth=0.279)

        self.Text2.configure(background="white")
        self.Text2.configure(font="-family {DejaVu Sans} -size 12")
        self.Text2.configure(selectbackground="#c4c4c4")
        self.Text2.configure(width=356)
        self.Text2.configure(wrap="word")

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.047, rely=0.545, height=28, width=106)
        self.Label4.configure(activebackground="#82d88a")
        self.Label4.configure(background="#82d88a")
        self.Label4.configure(font="-family {Noto Sans CJK SC} -size 11 -weight bold -slant italic")
        self.Label4.configure(text='''Car No.''')

        self.Text3 = tk.Text(self.Frame1)
        self.Text3.place(relx=0.047, rely=0.607, relheight=0.044, relwidth=0.279)

        self.Text3.configure(background="white")
        self.Text3.configure(font="-family {DejaVu Sans} -size 12")
        self.Text3.configure(selectbackground="#c4c4c4")
        self.Text3.configure(width=356)
        self.Text3.configure(wrap="word")

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.392, rely=0.745, height=48, width=139)
        self.Button1.configure(activebackground="#8ced92")
        self.Button1.configure(background="#8dd888")
        self.Button1.configure(font="-family {Noto Sans CJK SC} -size 15 -weight bold -slant italic")
        self.Button1.configure(command = self.do,text='''Submit''')

if __name__ == '__main__':
    vp_start_gui()





