#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 10, 2019 02:27:22 PM IST  platform: Linux

import sys
from functools import partial


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import knn_login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    knn_login_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    knn_login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1301x744+65+24")
        top.title("New Toplevel")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.015, rely=0.027, relheight=0.948
                , relwidth=0.972)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#094209")
        self.Frame1.configure(highlightbackground="#49bbd8")
        self.Frame1.configure(width=1265)

        self.Label1 = tk.Label(top)
        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.142, rely=0.071, height=78, width=846)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#99ffc2")
        self.Label1.configure(font="-family {MathJax_Math} -size 23 -weight bold -slant italic")
        self.Label1.configure(text='''Welcome To Smart Residence''')

        self.Label2 = tk.Label(top)
        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.19, rely=0.34, height=38, width=126)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="#99ffc2")
        self.Label2.configure(font="-family {Noto Sans CJK SC} -size 13 -weight bold -slant italic")
        self.Label2.configure(text='''Username''')

        self.Label3 = tk.Label(top)
        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.198, rely=0.582, height=38, width=106)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(background="#99ffc2")
        self.Label3.configure(font="-family {Noto Sans CJK TC} -size 13 -weight bold -slant italic")
        self.Label3.configure(text='''Password''')

        self.Text1 = tk.Entry(top)
        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.198, rely=0.652, relheight=0.045, relwidth=0.313)

        self.Text1.configure(background="white")
        self.Text1.configure(font="-family {DejaVu Sans} -size 12")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(width=396)
        self.Text1.configure(wrap="word")

        self.Text2 = tk.Entry(top)
        self.Text2 = tk.Text(self.Frame1)
        self.Text2.place(relx=0.19, rely=0.411, relheight=0.045, relwidth=0.321)
        self.Text2.configure(background="white")
        self.Text2.configure(font="-family {DejaVu Sans} -size 12")
        self.Text2.configure(selectbackground="#c4c4c4")
        self.Text2.configure(width=406)
        self.Text2.configure(wrap="word")
        #self.Text2.configure(show="*")

        self.Button1 = tk.Button(top)
        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.482, rely=0.794, height=38, width=89)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(background="#45ff4b")
        self.Button1.configure(font="-family {Noto Sans CJK JP} -size 11 -weight bold -slant italic")
        self.Button1.configure(text='''Login''')
	login_handler = partial(knn_login_support.login_handler, self, top)
        self.Button1.configure(command=login_handler)
        


if __name__ == '__main__':
    vp_start_gui()





