#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    May 10, 2019 02:44:13 PM IST  platform: Linux

import sys
import MySQLdb
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    login_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None
def valid():
    usr = self.Text1.get('1.0','end')
    pas = self.Text2.get('1.0','end')
    sql = "select pass from users where usr = '"+usr+"'"
    dbc = MySQLdb.connect("localhost", "root", "Sneha@1998", "plate") 
    cursor = dbc.cursor()
    cursor.execute(sql)
    results = cursor.fetchall()
    if(pas is results):
    	entry.vp_gui_start()
    else:
		
class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font12 = "-family {Comic Sans MS} -size 18 -weight bold -slant"  \
            " italic -underline 0 -overstrike 0"
        font13 = "-family {Century Schoolbook L} -size 12 -weight bold"  \
            " -slant roman -underline 0 -overstrike 0"
        font9 = "-family {DejaVu Sans} -size 10 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("1366x713")
        top.title("New Toplevel")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=-0.007, rely=0.0, relheight=0.989, relwidth=0.999)

        self.Frame1.configure(relief='raised')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='raised')
        self.Frame1.configure(background="#000035")
        self.Frame1.configure(highlightthickness="2")
        self.Frame1.configure(width=1365)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.139, rely=0.043, height=68, width=1034)
        self.Label1.configure(activebackground="#030c0c")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(background="#d1edf2")
        self.Label1.configure(font=font12)
        self.Label1.configure(relief='ridge')
        self.Label1.configure(text='''Welcome To Smart Residence''')
        self.Label1.configure(width=1034)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.425, rely=0.695, height=31, width=181)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(background="#d1edf2")
        self.Button1.configure(font=font13)
        self.Button1.configure(text='''Login''')
        self.Button1.configure(width=181)

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.322, rely=0.312, height=31, width=149)
        self.Label2.configure(activebackground="#111111")
        self.Label2.configure(activeforeground="white")
        self.Label2.configure(activeforeground="#ffffff")
        self.Label2.configure(background="#d1edf2")
        self.Label2.configure(font=font13)
        self.Label2.configure(text='''Username''')
        self.Label2.configure(width=149)

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.322, rely=0.454, height=31, width=149)
        self.Label3.configure(background="#d1edf2")
        self.Label3.configure(font=font13)
        self.Label3.configure(text='''Password''')
        self.Label3.configure(width=149)

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.322, rely=0.369, relheight=0.034, relwidth=0.319)

        self.Text1.configure(font=font9)
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(width=436)
        self.Text1.configure(wrap='word')

        self.Text2 = tk.Text(self.Frame1)
        self.Text2.place(relx=0.322, rely=0.511, relheight=0.034, relwidth=0.319)

        self.Text2.configure(background="white")
        self.Text2.configure(font=font9)
        self.Text2.configure(selectbackground="#c4c4c4")
        self.Text2.configure(width=436)
        self.Text2.configure(wrap='word')

if __name__ == '__main__':
    vp_start_gui()





